#include "pch.h"
#include "Components.h"
#include "../Utility/ImGuiHelper.h"

namespace CMP316engine
{

	static void GetEditorCustomData(const PropertiesMap& properties, const char*& label, float& min, float& max)
	{
		if (auto it = properties.find("name"_hs); it != properties.end())
		{
			// Note that these casts will return nullptr if you supply the wrong type in the property map.
			label = *it->second.try_cast<const char*>();
		}
		if (auto it = properties.find("min"_hs); it != properties.end())
		{
			min = *it->second.try_cast<float>();
		}
		if (auto it = properties.find("max"_hs); it != properties.end())
		{
			max = *it->second.try_cast<float>();
		}
	}

	static bool DrawEditorFloat(float& f, const PropertiesMap& properties)
	{
		const char* label = "float"; // Use the type as the name incase a name wasn't registered in custom data.
		float min = 0;
		float max = 0;
		GetEditorCustomData(properties, label, min, max);

		return ImGuiHelper::InputAny(label, f);
		if (min != 0 || max != 0) {
			return ImGuiHelper::InputAny(label, f, min, max);
		}
		return ImGuiHelper::InputAny(label, f);
	}
	static bool DrawEditorFloat3(DirectX::XMFLOAT3& f, const PropertiesMap& properties)
	{
		const char* label = "float3";
		float min = 0;
		float max = 0;
		GetEditorCustomData(properties, label, min, max);

		if (min != 0 || max != 0) {
			return ImGuiHelper::InputAny(label, f, min, max);
		}
		return ImGuiHelper::InputAny(label, f);
	}
	static bool DrawEditorString(std::string& f, const PropertiesMap& properties)
	{
		const char* label = "string";

		if (auto it = properties.find("name"_hs); it != properties.end())
		{
			label = *it->second.try_cast<const char*>();
		}

		//return ImGui::InputText(name)
		return false;
	}

	/*
	Reflects the created components for autogenerated UI.
	Using reflection means instead of defining UI for specific components, I define
	for just the generic types (e.g. float, float3, std::string, etc).

	Any custom data, like a name, or a min and max for editor sliders will be placed inside my UnorderedMap of properties.

	HOW TO USE:
	For each component that should have reflected data, you should call entt::meta<ComponentType>(),
	then append calls to define the reflected data. (Entt chains them all together)
	
	Functions:
	.data should be set to the member variable you want to reflect.
	.traits uses my engine-defined traits to allow me to check what type of functionality is available to the member variable. You can use more than one trait, just call it more than once!!
	.custom is how you define custom data that reflection functions will check for. If you are wanting editor functionality, it is recommended you have 'name' so that you know what variable is being edited.
	You should only have ONE custom call per variable, add the extra data as an extra parameter. 
	Each custom variable added is a pair of the name the reflection systems will look for and the arbitrary value they are set to. I don't believe you can edit them at runtime, they should be treated as constants.
	Could use it for bools, floats, etc.
	*/
	void CMP316engine::InitializeReflection()
	{
		entt::meta_reset();
		
		/// THE FUNCTIONS

		entt::meta<float>().func<&DrawEditorFloat>("DrawEditor"_hs);
		entt::meta<DirectX::XMFLOAT3>().func<&DrawEditorFloat3>("DrawEditor"_hs);
		entt::meta<std::string>().func<&DrawEditorString>("DrawEditor"_hs);

		/// THE COMPONENTS

		entt::meta<TransformComponent>()
			// Hashed strings are used to give them unique identifiers. A macro could be used...
			// entt::as_ref_t means meta_any objects will not copy the data, which allows our DrawEditor* functions to work as they take a reference and modify it.
			.data<&TransformComponent::position, entt::as_ref_t>("position"_hs)
			// The properties map is used to register the label name of the field in the editor as well as things like the min and max for a slider.
			.custom<PropertiesMap>(PropertiesMap{ { "name"_hs, "position" } })
			.traits(Traits::EDITOR)
			.traits(Traits::SERIALIZE)
			.data<&TransformComponent::rotation, entt::as_ref_t>("rotation"_hs)
			.custom<PropertiesMap>(PropertiesMap{ { "name"_hs, "rotation" }, { "min"_hs, -180.f }, { "max"_hs, 180.f } })
			.traits(Traits::EDITOR)
			.data<&TransformComponent::scale, entt::as_ref_t>("scale"_hs)
			.custom<PropertiesMap>(PropertiesMap{ { "name"_hs, "scale" } })
			.traits(Traits::EDITOR)
			.data<&TransformComponent::testFloatInTransform, entt::as_ref_t>("testFloatInTransform"_hs)
			.custom<PropertiesMap>(PropertiesMap{ { "name"_hs, "testFloatInTransform" } })
			.traits(Traits::EDITOR)
			;

		entt::meta<ModelComponent>()
			.data<&ModelComponent::filepath, entt::as_ref_t>("filepath"_hs)
			.custom<PropertiesMap>(PropertiesMap{ { "name"_hs, "filepath" } })
			.traits(Traits::EDITOR)
			;
	}
}